### ISSUE TITLE
Template Upload and Guidelines

### ISSUE THREAD

**Issue by 99003730** [99003732/Team2#1]
Hi Guys I uploaded the project template by the name of Mini Project Calculator on Team2 Repository, here are few tips I like to give which will make our work a lot easier
1. When commit change type your name , then the action you did and the file name, for example I updated readme.md, the commit would be Arnav Update readme.md.
2. Always push your code to a Branch and then create a pull request and raise A NEW ISSUE for the same asking any suggestions or improvements.
**Please Acknowledge by typing Yes in the reply  and the last person to write will also close this issue.**

**Comment by 99003732** [comment]
Yes

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by 99003729** [comment]
ok..

**Comment by 99003728** [comment]
okie
